//! The dependency lockfile (`phorj.lock`) — exact, reproducible pins.
//!
//! `phg vendor` writes this file; nothing reads it to *fetch* (resolution is offline — the
//! committed `vendor/` is the source of truth at run time). The lock records, per `[require]`
//! dependency, the **resolved commit SHA** (`rev` — the cryptographic pin a tag/rev was resolved to)
//! and a **content `hash`** of the vendored tree (FNV-1a-64, reused from [`crate::bundle::cross`]; a
//! non-cryptographic integrity checksum — the SHA is the real pin). Its purpose is determinism and
//! drift detection: a reviewer can see exactly what was vendored, and a future `phg vendor` can
//! reproduce it (M5-10 / O-7).
//!
//! The format is the same deliberately-small TOML subset the manifest uses, in `[[package]]`
//! array-of-tables form. It is strict: a missing field, an unknown key, or an unquoted value is a
//! hard error rather than silent acceptance.

/// One locked dependency: the resolved, reproducible coordinates of a vendored package.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LockEntry {
    /// Composer-style `vendor/package` name (matches the manifest `[require]` key).
    pub name: String,
    /// Git URL the dependency was fetched from.
    pub git: String,
    /// Resolved full commit SHA the pin (tag/rev) was resolved to — the cryptographic pin.
    pub rev: String,
    /// FNV-1a-64 (hex, 16 digits) of the vendored source tree — a content integrity checksum.
    pub hash: String,
}

/// A parsed `phorj.lock`: the locked dependency set, in manifest order.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Lock {
    pub packages: Vec<LockEntry>,
}

impl Lock {
    /// The lockfile name, written at the project root beside `phorj.toml`.
    pub const LOCK_FILE: &'static str = "phorj.lock";

    /// Render the lockfile text. Deterministic: entries in their stored order, fixed key order, a
    /// leading do-not-edit banner. The output round-trips through [`Lock::parse`].
    pub fn render(&self) -> String {
        let mut out = String::from(
            "# phorj.lock — generated by `phg vendor`. Do not edit by hand.\n\
             # Each [[package]] pins a [require] dependency to a resolved commit + content hash.\n",
        );
        for p in &self.packages {
            out.push_str("\n[[package]]\n");
            out.push_str(&format!("name = {}\n", quote(&p.name)));
            out.push_str(&format!("git = {}\n", quote(&p.git)));
            out.push_str(&format!("rev = {}\n", quote(&p.rev)));
            out.push_str(&format!("hash = {}\n", quote(&p.hash)));
        }
        out
    }

    /// Parse a `phorj.lock` from its text. Returns a human-readable, line-numbered error on any
    /// malformed or unsupported construct.
    pub fn parse(text: &str) -> Result<Lock, String> {
        let mut packages: Vec<LockEntry> = Vec::new();
        // The current entry's fields, filled until the next `[[package]]` or EOF flushes them.
        let mut cur: Option<PartialEntry> = None;

        for (i, raw) in text.lines().enumerate() {
            let lineno = i + 1;
            let line = strip_comment(raw).trim();
            if line.is_empty() {
                continue;
            }
            if line == "[[package]]" {
                if let Some(p) = cur.take() {
                    packages.push(p.finish(lineno)?);
                }
                cur = Some(PartialEntry::default());
                continue;
            }
            if line.starts_with('[') {
                return Err(format!(
                    "phorj.lock:{lineno}: unexpected section `{line}` (only [[package]] is allowed)"
                ));
            }
            let (k, v) = line.split_once('=').ok_or_else(|| {
                format!("phorj.lock:{lineno}: expected `key = value`, found `{line}`")
            })?;
            let entry = cur.as_mut().ok_or_else(|| {
                format!(
                    "phorj.lock:{lineno}: `{}` appears before any [[package]]",
                    k.trim()
                )
            })?;
            let value = parse_string(v).map_err(|e| format!("phorj.lock:{lineno}: {e}"))?;
            match k.trim() {
                "name" => entry.name = Some(value),
                "git" => entry.git = Some(value),
                "rev" => entry.rev = Some(value),
                "hash" => entry.hash = Some(value),
                other => {
                    return Err(format!(
                        "phorj.lock:{lineno}: unknown key `{other}` (expected name, git, rev, or hash)"
                    ));
                }
            }
        }
        if let Some(p) = cur.take() {
            packages.push(p.finish(text.lines().count())?);
        }
        Ok(Lock { packages })
    }
}

/// Accumulator for one `[[package]]` block, validated into a [`LockEntry`] when the block closes.
#[derive(Default)]
struct PartialEntry {
    name: Option<String>,
    git: Option<String>,
    rev: Option<String>,
    hash: Option<String>,
}

impl PartialEntry {
    fn finish(self, lineno: usize) -> Result<LockEntry, String> {
        let need = |o: Option<String>, k: &str| {
            o.ok_or_else(|| format!("phorj.lock:{lineno}: [[package]] missing `{k}`"))
        };
        Ok(LockEntry {
            name: need(self.name, "name")?,
            git: need(self.git, "git")?,
            rev: need(self.rev, "rev")?,
            hash: need(self.hash, "hash")?,
        })
    }
}

/// Quote a value as a TOML basic string (the values here — names, URLs, hex — never contain a `"`).
fn quote(s: &str) -> String {
    format!("\"{s}\"")
}

/// Truncate a line at the first `#` not inside a double-quoted string (mirrors the manifest parser).
fn strip_comment(line: &str) -> &str {
    let mut in_quote = false;
    for (i, c) in line.char_indices() {
        match c {
            '"' => in_quote = !in_quote,
            '#' if !in_quote => return &line[..i],
            _ => {}
        }
    }
    line
}

/// Parse a strictly double-quoted TOML basic string (an unquoted value is an error).
fn parse_string(val: &str) -> Result<String, String> {
    let v = val.trim();
    if v.len() >= 2 && v.starts_with('"') && v.ends_with('"') {
        Ok(v[1..v.len() - 1].to_string())
    } else {
        Err(format!("expected a quoted string, found `{v}`"))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn entry(name: &str) -> LockEntry {
        LockEntry {
            name: name.to_string(),
            git: format!("https://example.com/{name}.phg"),
            rev: "0123456789abcdef0123456789abcdef01234567".to_string(),
            hash: "af63dc4c8601ec8c".to_string(),
        }
    }

    #[test]
    fn render_then_parse_round_trips() {
        let lock = Lock {
            packages: vec![entry("acme/strutil"), entry("acme/mathx")],
        };
        let text = lock.render();
        let back = Lock::parse(&text).unwrap();
        assert_eq!(lock, back);
    }

    #[test]
    fn empty_lock_round_trips() {
        let lock = Lock::default();
        let back = Lock::parse(&lock.render()).unwrap();
        assert!(back.packages.is_empty());
    }

    #[test]
    fn parses_a_known_layout() {
        let text = r#"
            # comment
            [[package]]
            name = "acme/strutil"
            git = "https://github.com/acme/strutil.phg"
            rev = "abc123"
            hash = "deadbeefcafef00d"
        "#;
        let lock = Lock::parse(text).unwrap();
        assert_eq!(lock.packages.len(), 1);
        assert_eq!(lock.packages[0].name, "acme/strutil");
        assert_eq!(lock.packages[0].git, "https://github.com/acme/strutil.phg");
        assert_eq!(lock.packages[0].rev, "abc123");
        assert_eq!(lock.packages[0].hash, "deadbeefcafef00d");
    }

    #[test]
    fn missing_field_errors() {
        let text = "[[package]]\nname = \"a/b\"\ngit = \"u\"\nrev = \"r\"";
        let err = Lock::parse(text).unwrap_err();
        assert!(err.contains("missing `hash`"), "got: {err}");
    }

    #[test]
    fn key_before_package_errors() {
        let err = Lock::parse("name = \"a/b\"").unwrap_err();
        assert!(err.contains("before any [[package]]"), "got: {err}");
    }

    #[test]
    fn unknown_key_errors() {
        let text =
            "[[package]]\nname = \"a/b\"\ngit = \"u\"\nrev = \"r\"\nhash = \"h\"\nfoo = \"x\"";
        let err = Lock::parse(text).unwrap_err();
        assert!(err.contains("unknown key `foo`"), "got: {err}");
    }

    #[test]
    fn unexpected_section_errors() {
        let err = Lock::parse("[require]\nx = \"y\"").unwrap_err();
        assert!(err.contains("unexpected section"), "got: {err}");
    }

    #[test]
    fn unquoted_value_errors() {
        let text = "[[package]]\nname = acme/strutil";
        let err = Lock::parse(text).unwrap_err();
        assert!(err.contains("expected a quoted string"), "got: {err}");
    }
}
